#!/bin/sh
# This is a placeholder. The real gradlew is generated by Android Studio
# or can be downloaded by running:
#   gradle wrapper
# from the project root (requires Gradle installed locally).
#
# GitHub Actions will use the pre-generated wrapper files.
# For local development, open this project in Android Studio and it
# will automatically generate the gradlew script and gradle-wrapper.jar.
echo "Please open this project in Android Studio to generate the Gradle wrapper."
echo "Or run: gradle wrapper --gradle-version=8.4"
